[font]
normal = ["Iosevka Nerd Font"]
#normal = ["Berkeley Mono", "Iosevka Nerd Font", "Operator Mono Lig"]
#normal = ["Operator Mono Lig", "Operator Mono", "Iosevka Nerd Font"]

size = 12
hinting = "full"
edging = "subpixelantialias"

[font.features]
"Operator Mono Lig" = ["liga"]
