[font]
#normal = ["MonaspiceKr Nerd Font"]
3normal = ["MonaspiceAr Nerd Font"]
#normal = ["MonaspiceNe Nerd Font"]
#normal = ["Iosevka Nerd Font"]
size = 15
hinting = "full"
edging = "subpixelantialias"

[font.features]
"Iosevka Nerd Font" = ["liga", "+ss08"]
"Monaspace Neon" = [
  "liga",
  "calt",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss06",
  "+ss07",
  "+ss08",
  "+ss09",
]
"Monaspace Argon" = [
  "liga",
  "calt",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss06",
  "+ss07",
  "+ss08",
  "+ss09",
]
"Monaspice*" = [
  "liga",
  "calt",
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss06",
  "+ss07",
  "+ss08",
  "+ss09",
]
